import { ReactElement } from 'react'
import Head from 'next/head'
import Hero from 'src/features/home/views/Hero'
import HomeLayout from 'src/features/home/views/Layout'
import { NextPageWithLayout } from './_app'
import Image from 'next/image'

const HomePage: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Webatool Web Accessibility</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <div className='flex flex-row w-full py-20'>
        <div className='basis-1/2'>
          <div className='text-6xl mt-5 text-purple-700'>Visual</div>
          <div className='text-6xl text-purple-700'>Analytics Reports</div>
        </div>
        <div className='basis-1/2 relative w-full'>
          <Image
            src="/images/reports.png"
            alt="Dashboard reports"
            width="1000"
            height="500"
          />
        </div>


      </div>
      <div className='text-center mb-5 clear-right'>
        <div> {'Copyright © '} webatool {new Date().getFullYear()}.</div>
      </div>
    </div>
  )
}

HomePage.getLayout = function getLayout(page: ReactElement) {
  return (<HomeLayout>
    {page}
  </HomeLayout>
  );
}

export default HomePage
